//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.Mobile.GuiTestRunner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.Mobile.GuiTestRunner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        internal static string AssemblyText {
            get {
                return ResourceManager.GetString("AssemblyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string ClassText {
            get {
                return ResourceManager.GetString("ClassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Messages.
        /// </summary>
        internal static string DebugMsgsText {
            get {
                return ResourceManager.GetString("DebugMsgsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        internal static string ErrorMessageText {
            get {
                return ResourceManager.GetString("ErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dll(s) are listed in the {0} file.
        /// </summary>
        internal static string ExceptionMissingDll {
            get {
                return ResourceManager.GetString("ExceptionMissingDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argumentfile {0} was not found.
        /// </summary>
        internal static string ExceptionMissingFile {
            get {
                return ResourceManager.GetString("ExceptionMissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed:.
        /// </summary>
        internal static string FailedText {
            get {
                return ResourceManager.GetString("FailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuiTestRunner.
        /// </summary>
        internal static string FormTitleText {
            get {
                return ResourceManager.GetString("FormTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MenuText {
            get {
                return ResourceManager.GetString("MenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed:.
        /// </summary>
        internal static string PassedText {
            get {
                return ResourceManager.GetString("PassedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string ResultsText {
            get {
                return ResourceManager.GetString("ResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Selected.
        /// </summary>
        internal static string RunSelText {
            get {
                return ResourceManager.GetString("RunSelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAllText {
            get {
                return ResourceManager.GetString("SelectAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        internal static string TabTestText {
            get {
                return ResourceManager.GetString("TabTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string TestText {
            get {
                return ResourceManager.GetString("TestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All.
        /// </summary>
        internal static string UnSelectAllText {
            get {
                return ResourceManager.GetString("UnSelectAllText", resourceCulture);
            }
        }
    }
}
