//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvp.Xml.TypedTemplate.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mvp.Xml.TypedTemplate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #error Couldn&apos;t generate code.
        ////*
        ///{0}
        ///*/.
        /// </summary>
        internal static string CustomTool_GeneralError {
            get {
                return ResourceManager.GetString("CustomTool_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool {0} does not contain the required {1} attribute..
        /// </summary>
        internal static string CustomTool_ToolRequiredAttributeMissing {
            get {
                return ResourceManager.GetString("CustomTool_ToolRequiredAttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse template..
        /// </summary>
        internal static string Template_CantParse {
            get {
                return ResourceManager.GetString("Template_CantParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute {0} has already been specified for directive {1}..
        /// </summary>
        internal static string Template_DuplicateDirectiveAttribute {
            get {
                return ResourceManager.GetString("Template_DuplicateDirectiveAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found &lt;?end?&gt; directive without a matching &lt;?foreach?&gt; or &lt;?if?&gt; starting directive..
        /// </summary>
        internal static string Template_EndWithoutStart {
            get {
                return ResourceManager.GetString("Template_EndWithoutStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template contains the following error at line {0}:
        ///{1}
        ///.
        /// </summary>
        internal static string Template_Exception {
            get {
                return ResourceManager.GetString("Template_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directive @ Import requires a Namespace attribute..
        /// </summary>
        internal static string Template_ImportDirectiveRequiresNamespace {
            get {
                return ResourceManager.GetString("Template_ImportDirectiveRequiresNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First line of the template must be the @Template directive..
        /// </summary>
        internal static string Template_MainDirectiveMissing {
            get {
                return ResourceManager.GetString("Template_MainDirectiveMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The @Template directive must contain the Output attribute specifying either XML or Text..
        /// </summary>
        internal static string Template_OutputMethodMissing {
            get {
                return ResourceManager.GetString("Template_OutputMethodMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directive @ Property requires a Name and Type attribute..
        /// </summary>
        internal static string Template_ProperyDirectiveMissingAttributes {
            get {
                return ResourceManager.GetString("Template_ProperyDirectiveMissingAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown code directive {0} found..
        /// </summary>
        internal static string Template_UnknownCode {
            get {
                return ResourceManager.GetString("Template_UnknownCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized directive {0}..
        /// </summary>
        internal static string Template_UnknownDirective {
            get {
                return ResourceManager.GetString("Template_UnknownDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must have the &apos;{1}&apos; attribute..
        /// </summary>
        internal static string Tool_AttributeMissing {
            get {
                return ResourceManager.GetString("Tool_AttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current project type can&apos;t have code elements, or can&apos;t compile to a .NET language. Supported project types are C# and VB.NET..
        /// </summary>
        internal static string Tool_NoCodeDomSupport {
            get {
                return ResourceManager.GetString("Tool_NoCodeDomSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get current project item..
        /// </summary>
        internal static string Tool_NoDTEProjectItem {
            get {
                return ResourceManager.GetString("Tool_NoDTEProjectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        internal static string Tool_Success {
            get {
                return ResourceManager.GetString("Tool_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output of type CodeDom must be either a CodeNamespace or a CodeCompileUnit..
        /// </summary>
        internal static string Tool_UnsupportedCodeDomOutput {
            get {
                return ResourceManager.GetString("Tool_UnsupportedCodeDomOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current project type is unsupported for this tool..
        /// </summary>
        internal static string Tool_UnsupportedProjectType {
            get {
                return ResourceManager.GetString("Tool_UnsupportedProjectType", resourceCulture);
            }
        }
    }
}
