//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.Mobile.TestTools.UnitTesting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.Mobile.TestTools.UnitTesting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.AreEqual failed. Expected:&lt;{0}&gt;, Actual:&lt;{1}&gt;..
        /// </summary>
        internal static string AssertAreEqual {
            get {
                return ResourceManager.GetString("AssertAreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.AreNotEqual failed. Not expected:&lt;{0}&gt;, Actual:&lt;{1}&gt;..
        /// </summary>
        internal static string AssertAreNotEqual {
            get {
                return ResourceManager.GetString("AssertAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.AreNotSame failed..
        /// </summary>
        internal static string AssertAreNotSame {
            get {
                return ResourceManager.GetString("AssertAreNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.AreSame failed..
        /// </summary>
        internal static string AssertAreSame {
            get {
                return ResourceManager.GetString("AssertAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.Fail failed..
        /// </summary>
        internal static string AssertFail {
            get {
                return ResourceManager.GetString("AssertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.IsFalse failed..
        /// </summary>
        internal static string AssertIsFalse {
            get {
                return ResourceManager.GetString("AssertIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.IsNotNull failed..
        /// </summary>
        internal static string AssertIsNotNull {
            get {
                return ResourceManager.GetString("AssertIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.IsNull failed..
        /// </summary>
        internal static string AssertIsNull {
            get {
                return ResourceManager.GetString("AssertIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.IsTrue failed..
        /// </summary>
        internal static string AssertIsTrue {
            get {
                return ResourceManager.GetString("AssertIsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsInstanceOfType.
        /// </summary>
        internal static string IsInstanceOfType {
            get {
                return ResourceManager.GetString("IsInstanceOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not throw expected exception..
        /// </summary>
        internal static string NoExceptionThrown {
            get {
                return ResourceManager.GetString("NoExceptionThrown", resourceCulture);
            }
        }
    }
}
