using System;
using System.Collections.Generic;

namespace Mvp.Xml.Synchronization
{
	public interface IXmlRepository
	{
		/// <summary>
		/// Returns the timestamp of the newly added item, as 
		/// generated by the underlying store.
		/// </summary>
		DateTime Add(IXmlItem item);
		bool Contains(string id);
		IXmlItem Get(string id);
		bool Remove(string id);

		/// <summary>
		/// Updates the given item. Throws KeyNotFoundException if
		/// the item was not already in this repository.
		/// </summary>
		DateTime Update(IXmlItem item);
		IEnumerable<IXmlItem> GetAll();
		IEnumerable<IXmlItem> GetAllSince(DateTime date);
		DateTime GetFirstUpdated();
		DateTime GetFirstUpdated(DateTime since);
		DateTime GetLastUpdated();
	}
}
